### ISSUE TITLE
add history pattern for scriptversions 

### ISSUE THREAD

**Issue by hanjoosten** [AmpersandTarski/RAP#10]
@stefjoosten , wil jij de .adl bestanden van RAP aanpassen, zodat we de versiegeschiedenis kunnen gebruiken voor scripts? 
- [ ] History pattern aanbrengen 
- [ ] Op elke historische versie van een script, waarbij er een context bestaat, moet op die context een requestDestroy worden gepopuleerd. 
- [ ] Interface "Nieuw script" moet worden aangepast: Destroy! moet vervallen

**Comment by stefjoosten** [comment]
# Requirements
Here is my interpretation of the requirements. Please correct me if there exist other ideas about this.
1. the user who submits a new version of a script (ScriptVersion) must experience that this item is inserted automatically at the head of the Sequence that corresponds to the Script.
2. the user who deletes a script must see the entire sequence removed.
3. ScriptVersions cannot be removed by the user.
4. The name of the assignment (`RELATION assignment[Script*Assignment]`) identifies the sequence. So it must correspond to `RELATION seqName[Sequence*SeqName]`.

**Comment by stefjoosten** [comment]
# Situation
Before diving deeper into this, I want to see where we stand. So I start with the current situation. Then I will argue which measures are appropriate to get this done.

I see that @hanjoosten has already taken some measures, which I second:
~~~~~~
CLASSIFY Script ISA Sequence
CLASSIFY ScriptVersion ISA Item
~~~~~~
Rieks has made a test-interface, in which the correct functioning of sequences can be verified:
![image](https://cloud.githubusercontent.com/assets/275768/19758754/dc4268b6-9c29-11e6-98c3-be1ade7e4417.png)
This is quite useful to experiment with. It allows you to insert items at the head and the tail of the list. It also allows to delete and remove arbitrary items. I think "remove" means that the item is taken from the list, but stays existant. I think that "delete" means that the item is taken from the list and deleted. In both cases, the rest of the list remains intact.

The logical data model of RAP3 (compiled without meta-tables) is useful for the discussion.
![logicaldatamodel](https://cloud.githubusercontent.com/assets/275768/19758865/a978e800-9c2a-11e6-8ebf-d22fa326d7b2.png)

**Comment by stefjoosten** [comment]
# Analysis
## New Script
Because `Script ISA Sequence`, insertion of a new `Script` does not require insertion of a new `Sequence`.

When the user makes or deletes an assignment, I propose to create and delete the corresponding sequence. This requires two automated rules:

    RULE assignment |- seqName  -- to administer a new assignment and populate the sequence if so required.
    RULE seqName |- assignment  -- to administer removal of an assignment.

For this, it is necessary to add

    CLASSIFY Assignment ISA SeqName

Because `Sequence`s may be empty, the first item can be inserted in due time.

## Inserting a new item
In SeqItems.ifc, the relation `seqNewFirstItem` is used to specify the name of an `Item` that is to be created and inserted as a new first item in a `Sequence`.
The service SeqInterfacing.svc uses the following logic to insert a new first item in a sequence:
~~~~~~
RELATION seqNewFirstItem[Sequence*ItemName] [UNI] -- Create a new Item called 'ItemName', inserting it as the first Item

ROLE ExecEngine MAINTAINS "Create a 'new first item' in a non-empty sequence"
RULE "Create a 'new first item' in a non-empty sequence":
   (I /\ itemInSeq~;itemInSeq);seqNewFirstItem |- seqFirstItem;itemName
VIOLATION (TXT "{EX} NewStruct;Item"
               ,TXT ";itemInSeq;Item;_NEW;Sequence;", SRC I
               ,TXT ";itemName;Item;_NEW;ItemName;", TGT I
               ,TXT ";nextItem;Item;_NEW;Item;", SRC seqFirstItem
          ,TXT "{EX} DelPair;seqNewFirstItem;Sequence;", SRC I, TXT ";ItemName;", TGT I
          )
~~~~~~
So in RAP3, I propose to use the relation `version` for that same purpose and reuse the logic to insert a new first item.
When `RELATION version[Script*ScriptVersion]` is populated, we know that there is a `ScriptVersion` and therefore also an `Item`.

**Comment by Michiel-s** [comment]
Be aware that the history pattern adds rules that need be be evaluated for every update. This might become a performance issue. History pattern is nice to demo the wanted behavior, but not the most efficient way to implement it. Since RAP3 becomes a production application only do this when really necessarily. As discussed this afternoon, there are other ways to let students see the history of their scripts; using a datitime.
