### ISSUE TITLE
RAP brings user back to log in page

### ISSUE THREAD

**Issue by LloydRutledge** [AmpersandTarski/RAP#103]
A student has reported that she and several other students repeatedly get this behavior. They describe one such incident as: 

"When I click open the atlas, I get sent back. When I change some code and press compile, I am redirected back to login page. To log in at all, I the loading page for about 20 seconds before allowing me to interact with it. To open Atlas (if successful) it also takes 20 seconds for it to open."

Get sent back to the log in is probably a different issue than the 20 second delay. Getting sent back is clearly behavior the system is not supposed to do. The delay is not buggy behavior but expected behavior unexpectedly slow, which can be caused by many things even with good code.

Is there a way to track down and fix the redirection bug? And/or can we offer the students now and for the short term some workaround interaction patterns?

**Comment by stefjoosten** [comment]
This seems to have vanished without a proper diagnosis being made. Please reopen if it reoccurs

**Comment by attaxia** [comment]
@stefjoosten  Please reopen this ticket, it is still occurring. For most of today I didn't have this issue, but for the last 30-60 minutes I'm being kicked out every minute.

**Comment by stefjoosten** [comment]
I have no clue. I really wouldn't know what to look for. If other students have this behaviour too (like @attaxia) please try to describe what happens. Maybe we can analyze towards a proper diagnosis if we get to see more symptoms.

**Comment by attaxia** [comment]
My entire study group has it and during the lectures multiple people were complaining about it. My reprodution path is as follows, although the issue is intermittent:

# Log in
# Paste in a script
# Click compile
# Do nothing / generate and play with prototype for 10/20 seconds
# Make a small change in script
# Click compile
# RAP redirects to login page

**Comment by attaxia** [comment]
I have a reproduction path. The issue is when there is more than one user logged in to the system.
To test this I used two different browsers (cookies cleared) both using a different VPN to ensure that no IP based logic was going on.

As soon as a second user logs in the first user is logged out.

https://user-images.githubusercontent.com/4743303/103416476-40841c00-4b87-11eb-8365-1e6715607517.mp4

**Comment by stefjoosten** [comment]
Thanks for this report, @attaxia. I watched your clip a few times. I cannot make out precisely what is happening, because I don't see the mouse-arrow and I don't hear mouse clicks. But what I make of it is this. When you are logged in on the left screen as user "aaa", and someone else logs in on the right screen as user "bb", the session of person "aaa" is killed. If that is what happens, it surely explains this behavior.

# Analysis
I have reproduced this by using another browser. This is the reproduction path.
1. Open two different browsers (e.g. Chrome and Firefox)
2. On browser A, log in as user "aaa" and do stuff (edit, run prototypes, whatever, even do nothing).
3. On browser B, log in as user "bb". My hypothesis is that this kills the session of user "aaa"

This is a hypothesis I can analyze. 
It also explains the behavior you get and why it feels erratic. Effectively it would mean that if more than one person logs in, she effectively kicks out the others.

**Comment by stefjoosten** [comment]
@attaxia said:
> @stefjoosten Please reopen this ticket, it is still occurring. For most of today I didn't have this issue, but for the last 30-60 minutes I'm being kicked out every minute.

If my analysis is correct, you must have been working alone for most of the day. Somewhere in the last 30-60 minutes a fellow student used RAP4 as well and you might have been kicking each other out of the system all the time...

**Comment by attaxia** [comment]
> Thanks for this report, @attaxia. I watched your clip a few times. I cannot make out precisely what is happening, because I don't see the mouse-arrow and I don't hear mouse clicks. But what I make of it is this: When you are logged in on the left screen as user "aaa", and someone else logs in on the right screen as user "bb", the session of person "aaa" is killed. If that is what happens, it surely explains this behavior.
> 
> # Analysis
> I have reproduced this using two different browsers. Here is what I did:
> 
> 1. I opened two different browsers (Chrome and Firefox) to make sure that both sessions do not interfere.
> 2. On Chrome, I logged in as user "hero2" and did stuff (edit, run prototypes).
> 3. On Firefox, I logged in as user "stefj". From this moment, the session on Chrome required a new login. My hypothesis is that this killed the session of user "hero2"
> 
> This is a hypothesis I can chase.
> It definitely explains the behavior you get and why it feels erratic. Effectively it would mean that if more than one person logs in, she effectively kicks out all others. So let's see what further analysis shows ...

This is indeed what happens. There is a arrow though in my clip, it’s black. But I recorded on a 27 inch screen and had to reduce the resolution of the video file to be able to upload. Oops.

**Comment by stefjoosten** [comment]
# Analysis
A proof that a second session can kill the first session is in file [rap4.log](https://github.com/AmpersandTarski/RAP/files/5759204/rap4.log). So what was a hypothesis at first ([in this comment](https://github.com/AmpersandTarski/RAP/issues/103#issuecomment-753273950)) we now know as a fact. In the log file I have added the user events by hand to make the file more readable. It is self-evident on which lines I did that.

I did the following user events:
1. type "localhost" in the URL-bar of the browser
2. navigate to the login screen
3. push the LOGIN button (userid and password fields have been filled by the browser)
4. navigate to MyScripts
5. navigate to an existing script
6. Firefox kicks in on URL localhost.
7. go back to Chrome by clicking on it.

In response to event 6, line 403 of this log file contains the proof that the session in Chrome is deleted:
```
[2021-01-01 16:48:16] EXECENGINE.INFO: ExecEngine fixing 1 violations for rule 'Logout without request' [] {"request_id":"529c9bf861","ip":"172.18.0.5","method":"GET","url":"/api/v1/app/navbar"}
[2021-01-01 16:48:16] EXECENGINE.INFO: Fixing violation 1/1: ((2e990c61ae4beb348f4b9011ba0fa026[SESSION],2e990c61ae4beb348f4b9011ba0fa026[SESSION])) [] {"request_id":"529c9bf861","ip":"172.18.0.5","method":"GET","url":"/api/v1/app/navbar"}
[2021-01-01 16:48:16] EXECENGINE.INFO: DelPair(sessionAccount,SESSION,2e990c61ae4beb348f4b9011ba0fa026,Account,Acc_Stef) [] {"request_id":"529c9bf861","ip":"172.18.0.5","method":"GET","url":"/api/v1/app/navbar"}
[2021-01-01 16:48:16] CORE.INFO: Link deleted: (2e990c61ae4beb348f4b9011ba0fa026[SESSION],Acc_Stef[Account]) sessionAccount[SESSION*Account] [] {"request_id":"529c9bf861","ip":"172.18.0.5","method":"GET","url":"/api/v1/app/navbar"}
```
So RAP4 deletes the session in Chrome even before any user action in Firefox. Merely going to the URL already trashes the session in Chrome. It is the rule `Logout without request` that is violated for the session in Chrome. So that is where our diagnosis starts. I guess that user events 4 and 5 could have been skipped to get the same result.

**Comment by stefjoosten** [comment]
# Diagnosis
The culprit is the following rule from file `RAP4_AccountMgt.ifc`(line 139):
```
RULE "Logout without request":
   I /\ sessionAccount;sessionAccount~ |- "_SESSION"
```
This rule is clearly wrong because it allows only one session, which is `"_SESSION"`. This explains why the ExecEngine kills all other sessions, which is the behavior we saw in the file [rap4.log](https://github.com/AmpersandTarski/RAP/files/5759233/rap4.log).

The reason for having this rule in the first place was documented in the PURPOSE: "When a session ceases to exist, RAP4 will break the link between session and account.". In the code, we see that the session is deleted from the database, which implicitly deletes the pair in `sessionAccount`. So rule `Logout without request` is not needed at all.

The solution is therefore to delete this rule from RAP4.

**Comment by stefjoosten** [comment]
@attaxia , Thank you for your help with this issue. Without that help we would have been stuck.
