### ISSUE TITLE
Old sessions should be removed

### ISSUE THREAD

**Issue by hanjoosten** [AmpersandTarski/RAP#113]
This happend just after the deployment of the PR that fixes https://github.com/AmpersandTarski/RAP/issues/103:

I registered with a fresh new account. Then I was guided to the screen where I am supposed to alter my password. It doesn't look right, as can be seen on this screenshot:

![image](https://user-images.githubusercontent.com/1159672/103454761-75a78000-4ce7-11eb-81cc-f6c7e1b56995.png)

**Comment by RieksJ** [comment]
If RAP is using its own, local version of SIAM (which I suspect is the case), you can simply add the UNI constraint, as indeed, `sessionAccount` must have it. The 'official' RAP versions have specified this constraint.

**Comment by attaxia** [comment]
@RieksJ This also seems to happen on the "official" RAP page:
<img width="1179" alt="Screen Shot 2021-01-04 at 15 44 13" src="https://user-images.githubusercontent.com/4743303/103546756-cb288c00-4ea3-11eb-87ab-a998461a52e9.png">

**Comment by RieksJ** [comment]
The problem is that `sessionAccount` is not INJ, and that for a single Account, multiple sessions could exist: the expression that leads to the multiple rows, is `sessionAccount~`, and if for a single account there are multiple sessions (which shouldn't be the case), that's the behaviour you get.

**Comment by stefjoosten** [comment]
The following is to demonstrate the consequences of `RULE "Remove expired sessions"`.
I have run 4 sessions in parallel, all with the same username/password, to cause multiple sessions of the same user simultaneously. Without the mentioned rule, all steps should work just fine. With the rule in place, we can expect errors. I ran the following event sequence (all events went OK, except when noted that it yielded an error):

1. Session 1: Home   (by means of GET http://localhost/)
2. Session 2: Home
3. Session 1: Display the login screen   (by means of GET http://localhost/api/v1/resource/SESSION/1/Login)
4. Session 2: Display the login screen
5. Session 1: Fill Userid/Password     (by means of PATCH http://localhost/api/v1/resource/SESSION/1)
6. Session 1: Display MyScripts     (by means of GET http://localhost/api/v1/resource/SESSION/1/MyScripts)
7. Session 2: Fill Userid/Password
8. Session 2: Display MyScripts
9. Session 1: Ask for a New Script     (by means of POST http://localhost/api/v1/resource/Script)
10. Session 3: Home
11. Session 2: Ask for a New Script
12. Session 1: Display New Script   (by means of GET http://localhost/api/v1/resource/Script/Script_f6274b91-a346-4730-b234-802433dabc73/Nieuw_32_script)
13. Session 2: Display New Script   (by means of GET http://localhost/api/v1/resource/Script/Script_56340202-e055-485b-bc54-2756c3fd79b1/Nieuw_32_script)
14. Session 3: Display the login screen
15. Session 1: Type New Script   (by means of PATCH http://localhost/api/v1/resource/Script/Script_f6274b91-a346-4730-b234-802433dabc73/Nieuw_32_script)
16. Session 2: Type New Script   (by means of PATCH http://localhost/api/v1/resource/Script/Script_56340202-e055-485b-bc54-2756c3fd79b1/Nieuw_32_script)
17. Session 3: Fill Userid/Password
18. Session 3: Display MyScripts
19. Session 2: Compile the Script    This comes back with a "not found" error (401 Unauthorized).
Hypothesis: Session 3 has deleted the session identifier of session 2, which explains this error
20. Session 3: Ask for a New Script
21. Session 3: Display New Script
22. Session 4: Home
23. Session 2: Show the Atlas     This comes back with a "not found" error (401 Unauthorized).
Hypothesis: Session 3 has deleted the session identifier of session 2, which explains this error
24. Session 3: Type New Script
25. Session 1: Compile the Script
26. Session 4: Display the login screen
27. Session 1: Functional Specification     This comes back with a "not found" error (401 Unauthorized).
Hypothesis: Session 2 has deleted the session identifier of session 1, which explains this error
28. Session 4: Fill Userid/Password
29. Session 4: Display MyScripts
30. Session 1: Prototype     This comes back with a "not found" error (401 Unauthorized).
Hypothesis: Session 2 has deleted the session identifier of session 1, which explains this error
31. Session 4: Ask for a New Script
32. Session 1: Show the Atlas     This comes back with a "not found" error (401 Unauthorized).
Hypothesis: Session 2 has deleted the session identifier of session 1, which explains this error
33. Session 3: Compile the Script
34. Session 4: Display New Script
35. Session 3: Functional Specification     This comes back with a "not found" error (401 Unauthorized).
Hypothesis: Session 4 has deleted the session identifier of session 3, which explains this error
36. Session 4: Type New Script
37. Session 3: Prototype     This comes back with a "not found" error (401 Unauthorized).
Hypothesis: Session 4 has deleted the session identifier of session 3, which explains this error
38. Session 3: Show the Atlas     This comes back with a "not found" error (401 Unauthorized).
Hypothesis: Session 4 has deleted the session identifier of session 3, which explains this error
39. Session 4: Compile the Script
40. Session 4: Functional Specification
41. Session 4: Prototype
42. Session 4: Show the Atlas

I cannot explain why for example Step 15 is successful. I would expect that it fails because by the time it occurs session 2 will have deleted the session identifier of session 1.

**Comment by RieksJ** [comment]
There is a 'frontend session' - some artifact between the browser and the web server which is distinct from the `SESSION` concept, and they're not always in sync. My guess is that this is somehow relevant to explain what happens in your example.

I recall having requested @Michiel-s to 'sync' them (deleting one if the other is deleted, and creating one if another is created), but for one reason or another that was difficult (I have looked for, but not found any issues on that). Perhaps this has to do with the fact that a browser can only have a single (frontend-)session with a web server (different tabs are still the same session), but I'm not sure.

**Comment by stefjoosten** [comment]
In the meantime, I can explain why Step 15 is successful. Apparently, this step can go  on because Ampersand has no violations. The first error, in event 15, is not a violation of an Ampersand rule.

**Comment by stefjoosten** [comment]
@RieksJ  writes:
> There is a 'frontend session' - some artifact between the browser and the web server which is distinct from the `SESSION` concept, and they're not always in sync. My guess is that this is somehow relevant to explain what happens in your example.
> 
> I recall having requested @Michiel-s to 'sync' them (deleting one if the other is deleted, and creating one if another is created), but for one reason or another that was difficult (I have looked for, but not found any issues on that). Perhaps this has to do with the fact that a browser can only have a single (frontend-)session with a web server (different tabs are still the same session), but I'm not sure.

I would be nice that the browser signals the end of a session. After all, a session originates in the browser. However, if the browser suddenly ceases to work, there is no way it can signal the end of its sessions. For this reason servers usually place a time constraint on session. If nothing happens during a period of time, the server assumes the session has ceased to exist. Nevertheless, most sessions end because the user fails to logout. I'm sure the client could do useful things to signal that to the server, but this will never be an all-comprising signal. So the time constraint with the server will have to remain in place.

**Comment by Michiel-s** [comment]
> @RieksJ says:
> There is a 'frontend session' - some artifact between the browser and the web server which is distinct from the `SESSION` concept, and they're not always in sync. My guess is that this is somehow relevant to explain what happens in your example.

This is not true. Ampersand session id and browser session id are the same. Furthermore we've implemented session renewal after privilege change (e.g. login/logout), according to best practice: https://cheatsheetseries.owasp.org/cheatsheets/Session_Management_Cheat_Sheet.html#renew-the-session-id-after-any-privilege-level-change

If however the user closes the browser, we don't know that the session can be deleted. This will leave expired sessions in the database. Once the user returns with the same session id after expiration time, it will be renewed anyway and the old one deleted. The backend will take care of this.
Cleaning up expired sessions is hard to specify in Ampersand because we cannot specify calculation rules. If needed you can manually trigger cleanup: `GET api/v1/admin/sessions/delete/expired`
