### ISSUE TITLE
Blank screen when Interface 'Context' should be shown

### ISSUE THREAD

**Issue by hanjoosten** [AmpersandTarski/RAP#12]
In RAP, I get a blank screen, where there should be a normal interface showing. 

To reproduce: (I've had this myself, and I have seen the same behaviour at Rieks's machine, and tonight also at that of Stef.)

1) Use ampersand.exe (built from ampersand/developement branch) 
2) Use Rap3.adl (ampersand-models/rap3 branch)
3) Generate the prototype, using the flags  --meta-tables -pYourFavoriteProtoDirWhatever
4) Fire up the prototype, it will install the database (otherwise, make sure it is 'fresh', by reinstalling the database)
5) Login as jan-de-student
6) Use + to make a new script. 
7) edit (or load) a valid script.
8) make sure you save it, using the blue 'Beware...' button. 
9) compile the script. A new 'scriptversion' will appear.
10) check the checkbox at 'Analyse'. The context of the script will be loaded into the database. A link to that context will appear. 

By now, the screen should look something similar to this one:

![image](https://cloud.githubusercontent.com/assets/1159672/20814938/05b7b3d2-b81c-11e6-93be-c6830b395f57.png)

11) Now click the link to the context.

Instead of the interface Context, (as specified in `Analyse.ifc`, which is included in the script), a more or less blank screen appears: 

![image](https://cloud.githubusercontent.com/assets/1159672/20815066/a35d32ec-b81c-11e6-9ace-5b5260ae15eb.png)

@Michiel-s Can you reproduce this? Do you have any idea what is going on?

**Comment by Michiel-s** [comment]
Ok. this is a tough one.

The error occurred in the browser due to a ' character in a template.

![image](https://cloud.githubusercontent.com/assets/7961582/20839422/d1c0cff0-b8ac-11e6-9351-b1e37ce5de3b.png)

The interface "Context" includes the interface "Patterns", waar een subinterface met label "Thema's" staat. De enkele quote hier zorgde voor een probleem in de SHCOLS template. Hier had de escaped variant gebruikt moeten worden. Ik zal bugfix in development branch inschieten voor betreffende templates.
