### ISSUE TITLE
thread blocked indefinitely in an MVar operation

### ISSUE THREAD

**Issue by stefjoosten** [AmpersandTarski/RAP#21]
# Symptoms
When compiling a functional specification of Hawaii in RAP3, I got a SLIM error. I reproduced this error on the Windows command line interface (CLI). There I found that nine picture files were generated correctly and the tenth made Ampersand crash, saying "thread blocked indefinitely in an MVar operation".
Here is the evidence:
![afbeelding](https://user-images.githubusercontent.com/275768/27991917-21f2726e-6486-11e7-81f0-f41c556f923a.png)
and here's how I repreduced the crash on the Windows CLI:
![afbeelding](https://user-images.githubusercontent.com/275768/27991936-b2abb608-6486-11e7-8601-09c0a5f798c7.png)

# Analysis
The error message itself originates from Haskell. It has to do with parallelization. Bug dialogs on the internet fuel the hypothesis that there is a bug somewhere in one of the Haskell libraries that RAP3 uses. This is a nasty bug, because it shadows the underlying cause making this nasty to diagnose. One good version of this story is on http://blog.omega-prime.co.uk/?p=92. If this hypothesis turns out to be the culprit, it affects the maintainability of Ampersand and should therefore be solved. (But not by us, if the bug resides in one of the libraries we use.) I think we should make the effort to track it down a little bit further.

Another possibility might be the length of filenames. The file that makes ampersand crash has 318 characters, which is more than the 260 prescribed by Windows. I dove into this, only to find out that this is tricky matter. The full story by Microsoft itself is on https://msdn.microsoft.com/en-us/library/aa365247.aspx#maxpath. I could not formulate a proper hypothesis based on this. To me, the length of the filename is an unlikely hypothesis, because we would have seen it on previous occasions when running Hawaii through RAP3. However, If I run the command with a short output filename, e.g. `\AmpersandJunkFiles\`, it runs without errors.

**Comment by stefjoosten** [comment]
I have asked Martijn for an opinion on this by assigning this one to him too. With his Haskell experience, he might have some inspiration we can use.

**Comment by hanjoosten** [comment]
Maybe it isn't as difficult as you suggest. What I see from the log is that Ampersand asks Graphviz to render an image. This might fail or it might succeed. Then at some point the image is being read, but that causes ampersand to crash. The image cannot be found. (the absolute pathname is pretty long, that might be a cause). In any case, ampersand crashes. It doesn't wake the thread it was spawend from. This seems to cause the problem. 
If this diagnose is true, catching the event and handling it properly will fix this bug. Then we can diagnose the root cause in this case, why the file cannot be found that Graphviz should have created just before.

**Comment by Oblosys** [comment]
The thread thing doesn't seem all that relevant to the bug. It's probably just sloppy programming in some package you're using, where a thread is spawned to compute some result which will be passed back with an MVar, and the thread gets an exception before writing to that MVar. The runtime then detects that a thread is waiting on reading an MVar to which no other references exist, and throws an exception instead of waiting indefinitely. Even if the code were to be cleaned up, it would still throw a file not found exception.

In Ampersand, you can add an exception handler to the place where you call this library, but that only gives you a more graceful way of failing. The real problem is that this file cannot be found. If you fix that, then you should be okay. Can you find the mentioned file at the time of the crash? The filename doesn't appear to be the issue, as the name itself is less than 3 lines, so less than 240 characters. The path is longer, but that should be okay.

PS If you use Windows PowerShell instead of the command prompt, you can copy lines instead of rectangles, so you can add actual output text to issues, instead of images.

**Comment by hanjoosten** [comment]
I added an exception handler. However, I cannot reproduce this. @stefjoosten , what does the error say?

**Comment by stefjoosten** [comment]
I get exactly the same error message.  I have compiled with Ampersand-v3.8.6 [development:49db30eaa], which is the version with your exception handler.  Again, if I replace the (long) OutputDir by the short `AmpersandJunkFiles` it works fine.

**Comment by stefjoosten** [comment]
To reproduce, run RAP3 on your local PC. Be sure to compile RAP3.adl with --meta-tables and --add-semantic-metamodel when generating.  I have compiled with Ampersand-v3.8.6 [development:49db30eaa], which is the version with your exception handler.  When it gives the Slim error, reproduce the generation in a Windows CLI, as shown above.

**Comment by Oblosys** [comment]
You could vary the length of the output dir to see at what total path length the problem occurs. If it's at 260, then it probably is the path length after all. Maybe just use a hash with a small name instead of the full string with all that information encoded? If the origin of the file is important, you could include a mapping between the short names and the longer ones somewhere in the generated code.

**Comment by stefjoosten** [comment]
This bug seems to have gone away. I'm closing it.
