### ISSUE TITLE
Create multiple CI/CD pipelines

### ISSUE THREAD

**Issue by FreekOrdina** [AmpersandTarski/RAP#251]
**Purpose**
To allow for deployment to multiple location, different pipelines should be setup:
- OU staging environment
- OU production environment
- Ordina development environment

**Task**

**Comment by FrankTeusink** [comment]
That's how I see it. Though on RAP repository we currently have 

- main branch, last commit Aug 15 2021,
- development branch, last commit Jan 17 2023,
- and a lot of other branches, of various ages.

So I think we should, for now have

- development branch as our core/master/main branch to collect all tested and approved code
- keep the real main branch as-is, and maybe discuss the intentional differences between main and development
- create feature branches based on development.

**Comment by FrankTeusink** [comment]
(for now) 3 stages: Local, Development and Staging.

Local is for deployment is to an environment created and maintained by a developer,
like a kubernetes cluster they created in their Visual Studio Subscription
For this, every developer can optionally create their own local environment 'Local{actor}' (i.e. 'LocalFrankTeusink')
Triggers on push to feature branches (i.e. with prefix 'feature/')
Deployment to this environment is optional
- if there exists a local environment for the initiating actor, named 'Local${actor}' 
- and if that environment contains a variable ENVIRONMENT_NAME with value 'Local{actor}'

Development is for deploying to the Development environment.
