### ISSUE TITLE
Functional spec describes RAP3 relations not part of the student's script

### ISSUE THREAD

**Issue by EstherHageraats** [AmpersandTarski/RAP#32]
See attached document for the script Enrollment.
[Version2017-11-24T163629.pdf](https://github.com/AmpersandTarski/RAP/files/1502073/Version2017-11-24T163629.pdf)

**Comment by hanjoosten** [comment]
This is intentionally. Let me try to describe what goes on. 

The user's script is compiled into a prototype. That prototype needs some default information about authorisations. At current, this information is defined as [an Ampersand script](https://github.com/AmpersandTarski/Ampersand/blob/development/AmpersandData/SystemContext/SystemContext.adl), because we eat our own dogfood :wink:

At current, we derive the Functional spec from exact the same context as the prototype is derived from. This causes these odd relations to appear in that document as well. In todays version of RAP3, the documentation of SystemContext.adl is still missing, but as you can see I updated it yesterday. In a next deployment these relations will remain present, but they are documented, so they will not cause warnings in the diagnosis. 

Maybe someday in the future we can get rid of this stuff in RAP3. This is well possible when we have a better theoretical insight about multiple contexts. This is ongoing research, and it will take time to have this implemented. Until then, users will have to cope with this, I presume.
