### ISSUE TITLE
Deadlock in MYSQL database

### ISSUE THREAD

**Issue by EstherHageraats** [AmpersandTarski/RAP#41]
A student reported an error mysql error 1213 (deadlock) during creating an account. see attached pdf that shows also the account being created.
![img-20171227-wa0010](https://user-images.githubusercontent.com/18698059/34453958-1b0047d4-ed60-11e7-902c-a3a7cf4cd586.jpeg)

we have no further information.

**Comment by hanjoosten** [comment]
Hmmm. This is pretty little info. conj_304 is probably the rule `Load population into meta tables`.

@EstherHageraats , could this student continue his session?

**Comment by Michiel-s** [comment]
I think this has to do with the rule violation cache in the database and the way it is updated after (re)evaluation of a conjunct. Probably the error occurred because two concurrent users where using RAP3 and, without being able to prevent this issue, causing the deadlock. 

See: https://stackoverflow.com/questions/2332768/how-to-avoid-mysql-deadlock-found-when-trying-to-get-lock-try-restarting-trans

This is an issue we should fix in the Ampersand prototype php backend code.

**Comment by Michiel-s** [comment]
See AmpersandTarski/Ampersand#635

**Comment by hanjoosten** [comment]
I closed this issue here, because it is an ampersand issue as @Michiel-s pointed out.
