### ISSUE TITLE
Space Leak Resolution

### ISSUE THREAD

**Issue by stefjoosten** [AmpersandTarski/RAP#52]
# Symptoms
Issues #43 and #45 report two incidents of disk space filling up. There is one month (30 days) time between those issues, and RAP3 consumed 5 GB in that period. The second incident was worse in the sense that the server wouldn't reboot anymore. This occured running RAP3 from commit fc8782f841ace8ec12366bcf04173eaad632b5dc on Dec 26th, 2017.

# Analysis
The consequences of this behaviour is that RAP3 is out of service. The risk is highest during the high season, so occurrence of this risk affects most students. As long as RAP3 is up and running on ``rap.cs.ou.nl``, I classify this as a normal prio bug. When it is down, the bug prio will be maximum.

The space usage is caused by excessive use of resources by RAP3:
1. Each time a student generates a prototype, that causes a complete application to be generated in the ``generate`` directory of that student.
2. For every prototype, a database is made.
3. The history of Ampersand scripts is kept both on disk and in the database.
4. A further analysis might uncover other excessive uses of resources.

There is no monitoring on space use by RAP3. In response to issue #43, @LloydRutledge is planning to create a way to monitor space use.

# Diagnosis
The cause of this incident being a space leak, we need short term actions and follow-up actions. Right now let us clear all the stuff students have generated, so as to preserve their script histories. In the follow-up we need to add functionality to RAP3 to prevent the excessive use of resources and learn the lessons from this experience.

# Actions (in brackets: action holder):
 - [x] Make ``http://ampersand.tarski.nl/RAP3`` available for students. (@stefjoosten)
 - [x] Tell students they can carry on on ``http://ampersand.tarski.nl/RAP3``. (@LloydRutledge )
 - [x] Ask ICTS for more space. This time, we'll fix the cause. For every GB of extra space we get, we "buy" a handful of days to fix stuff. So a few GB should suffice. More gives us more time to resolve. In [Lloyd's comment](https://github.com/AmpersandTarski/RAP/issues/43#issuecomment-355508579) he indicates we might get 6.7GB extra. I think 5GB will do and we can promise to give that 5 back within days (at most weeks). (@LloydRutledge)
 - [x] Bring ``rap.cs.ou.nl\RAP`` back on its feet. (@stefjoosten)
 - [x] clear all ``\generate`` directories of all students. (@stefjoosten)
 - [ ] remove all student databases from the database. (@stefjoosten)
 - [ ] fix the administration in the RAP3 database to comply with the above. (@stefjoosten)

In the follow-up, we must remove generated stuff automatically. Probably the best time to do that is when a student session ends. This requires a little more thought.

**Comment by stefjoosten** [comment]
Today, Peter Lambrikx has brought the server back up again, did a cleanup of old kernels (which seemed to have caused a failing reboot), and added 5 GB of disk space. I cleared another 6GB by deleting all ``\generate`` directories of all students. Next friday I will point the URL `ampersand.tarski.nl/RAP3` away from the Azure server and back to the OUNL server, giving students an opportunity to salvage any code they have made on ampersand.tarski.nl/RAP3.

**Comment by hanjoosten** [comment]
👍

**Comment by LloydRutledge** [comment]
I didn't record any monitoring last semester. Ik bekijk het minstens wekelijks in de komende cyclus en zal dan het opschrijven.

Is de current server emptied out from the previous cycle, so that this cycle's students don't have to share space with the students who finished last year?

**Comment by LloydRutledge** [comment]
During this holiday season the server filled up twice within one week. Both times the interface showed an SQL 1114 error, saying that a table became full. That is likely the consequence of the disk becoming full, which was indeed the case both times.

Stef's short-term solution both times was to delete files. The first time,  he deleted the log files. The second time, he also deleted generated functional specifications, images, and (interim) latex files.

But we expect heavier overflows in January. The server is somewhat busier now because the cycle has started, with 84 students. However, the real rush doesn't start until the coming weeks, after they've turned in their business case analysis and start then in earnest on the implementation, which is due the second week of February.

I've requested more disk space. And I'll keep checking the disk space and carefully deleting files from the given directories if necessary. However, it could be sweeping a broom against and ocean. And if the server keeps regularly going down, it will frustrate students.

Doesn't anyone have more short-to-middle term solutions? I've asked students to delete stored scripts on the server, thinking that may help. Are there more tips for the students? Or me, such as more directories whose files build up and I can delete safely?

Are any short-term changes possible in the software that will help? Such as cleaning up tables in SQL when not needed? Or zipping the (older) log files? Or zipping all files? How do other, comparable servers make their file system use more efficient? And is there perhaps another sort of leak as well?

**Comment by hanjoosten** [comment]
Asking students to remove scripts will hardly do anything. The amount of generated files is far greater. All generated files are stored in subdirectories that are named something like `generated` (I forgot the exact name, but inspection of the file system should tell you right away. 
I would advise to write a script that deletes all files in all such `generated` directories (including subfolders), that are older than x minutes/days/weeks. That should help quite a bit. This could cause students who inspect their scripts with removed files to encounter a bug, but they could easily recompile their script to get rid of those errors. 

For the long run we should build cleanup functionality into RAP itself,

**Comment by Michiel-s** [comment]
The solution that is really going to help is using a single deployment of the prototype framework (php backend and javascript frontend files). This is roughly 20 Mb, consisting of only 200 Kb of project/model specific files (generated output). The rest is all there to be able the run the prototype.

It probably would require some time to set it up, but you could make it so that the generic code is deployed once on the machine and the project specific files are loaded depending on the script that is requested. A change/issue in the Ampersand repo is required to support this way of deploying/running prototypes.

**Comment by LloydRutledge** [comment]
Per suggestion from @Michiel-s above, this issue is now at AmpersandTarski/Ampersand at https://github.com/AmpersandTarski/Ampersand/issues/880

**Comment by hanjoosten** [comment]
At its best the modification suggested by @Michiel-s is going to help partly, and also only on the long run. For the current hord of students, it will do nothing. For the short run, you will still have to periodically get rid of all \generated directories, as I suggested in my previous comment.
