### ISSUE TITLE
Something weird in FormalAmpersand?

### ISSUE THREAD

**Issue by stefjoosten** [AmpersandTarski/RAP#67]
#### Version of Ampersand and RAP
I am working with Ampersand-v3.17.0 [development:d30e6eb96], and RAP-commit ec006d96262b32f0d629227e76708abc611bf86d.

#### Problem
I was trying to generate a new version of RAP, using Ampersand-v3.17.0 as published on GitHub. That failed.

I ran the compiler with the following command:
```
BA92-C02VP224HTDF:RAP stefjoosten$ ampersand ./RAP3/RAP3dev.adl --config=./RAP3/RAP3dev.yaml -p/var/www/html/RAP3
```
I expected this compilation to go smoothly.

What happened is that I got the following message:
```
/Users/stefjoosten/git/RAP/RAP3/src/RAP3.adl:167:131 error:
  A relation is used that is not defined: context [Concept*Context]
```

**Comment by stefjoosten** [comment]
#### Analysis
My suspicion goes to FormalAmpersand, because the relation `context[Concept*Context]` should be defined there. I checked it, with the following findings:
* `AST.adl` contains an import statement to `Contexts.adl`
* `Contexts.adl` contains a definition of `context[Concept*Context]`.
So somehow Ampersand does not find this relation, even though it is declared.

**Comment by hanjoosten** [comment]
This error is by design. It is an early warning about differences in relations between the formal ampersand specification and the knowledge in Haskell source about how to populate these relations from a user's script.

This is how it works:

When the ampersand generator is used to do something with the formal ampersand model, a check is done that the relations known in `Transformers.hs` are the same as the relations defined in the specification of formal ampersand (the ADL script). Beware however: The version of your ADL script is not the current version on disk, but the version that was on disk when `ampersand.exe` was created. This is, because the ADL script of formalampersand is packed into `ampersand.exe`.

Thinking of this: @stefjoosten  Is this still an issue?

**Comment by hanjoosten** [comment]
If still an issue, feel free to reopen.
