### ISSUE TITLE
Generation of conceptual diagrams

### ISSUE THREAD

**Issue by hanjoosten** [AmpersandTarski/RAP#7]
For some reason, at this time not for all concepts, relations, rules and pattersn a conceptual model is generated. For the analysis to show conceptual models, they should be generated with a more friendly name.

**Comment by stefjoosten** [comment]
Conceptual diagrams in Ampersand are UGLY. We need some proper rethinking of the diagramming concept, so that users will start liking the (generated) diagrams. We want the (generated) text in a functional design to be illustrated with beautiful, useful, and consistent diagrams. And we need it built-in in the Ampersand-compiler (rather than "here-is-the-idea").

The following screenshot illustrates our problem. It was taken from a generated functional design.
![image](https://cloud.githubusercontent.com/assets/275768/21560402/189d03ea-ce5f-11e6-9e05-261549e3fdd0.png)

**Comment by hanjoosten** [comment]
Moved the remainder of this issue to Ampersand repo, where it belongs.
